easy:
    algo: ppo
    n_envs: 16
    n_steps: 256
    epoch: 3
    mini_batch_per_epoch: 8
    mini_batch_size: 2048
    gamma: 0.999
    lmbda: 0.95
    learning_rate: 0.0005
    grad_clip_norm: 0.5
    eps_clip: 0.2
    value_coef: 0.5
    entropy_coef: 0.01
    aug_coef: 0.1
    normalize_adv: True
    normalize_rew: True
    use_gae: True
    architecture: impala
    recurrent: False
